language: minimal
git:
  depth: false
services:
  - docker
before_script:
  - source ./config.sh
  - "./docker-login.sh"
  - docker-compose pull
  - docker-compose build
  - docker-compose up --no-build -d
  - docker-compose exec web /bin/sh -c "./wait-for-it.sh db:5432"
  - docker-compose exec web /bin/sh -c "bundle exec rails db:setup"
  - docker-compose exec web /bin/sh -c "bundle exec rake assets:precompile"
script:
  - docker-compose exec web /bin/sh -c "bundle exec rake spec"
  - docker-compose exec web /bin/sh -c "bundle exec govuk-lint-ruby app config db lib spec --format clang"
deploy:
  provider: script
  script: bash docker-push.sh
  skip_cleanup: true
  on:
    all_branches: true
    condition: "$TRAVIS_BRANCH =~ ^(master|staging|production)$"
env:
  global:
    secure: XUqFVqQur5ZoCCyAx7EF9VUEbDhUGd643Jki1FoYuDHLGRYZ275gX4EFqmqVuiAhsNIqcC+o4Ml66/0DeJ6kMEAQZNHT63KXLGPzi6LKDJ5qgxyh/0jr5Wwp1RwUPdxw73aZEBS8Fkg47xcwmY9Vx9BfHGA6pw/9DkxcbDI4fo3rlNXsxSkjg0uPosfD8XBbmoCtzCEu3J4EUVR7kZLfSmast62ID43xjOhf+xHyBe0uMV0cTLazRhvwayx8jfNJ4XMlMNzwWBj62uResGN6KA57x9h3UH31XckxeyUpjGVRdgQ0limAGqPa9eLPX4jTuH6I8oeRfd7WtaThf6db8/z+CIOHGdRy4HaMQs65ImjLh05mhujNBWNRyYdGm71IEHdfXOSFJqLsyXiCLTFCaONIUkCOA9/aiV+LN2hyyml9fAf6WqQGMCPWZDs7qrSZgIZ72q2mcRiY4GhNYP22kc+sDIGRSlomwO6fc8JtgCR62sXY19bj5fpXjNjzuH5plbg+m5VeA0bu5sRnj4Oo53MbtPaAYCRgQrmKZg2s6wE5W32goZxb/pRWtsE5/xAJ5ByhVql6sesA+8+NFwoDhfxMLH2GDV8lbtclkFQ/kUvgqH0LvRUV3uo0ftTkgSEyfmPrdG5xdXRra3sPjsB/V6SWW+rcYwfsNqtzjOemnLk=
