version: '3.2'
services:
  web:
    build:
      context: .
      cache_from:
        - ${dockerHubUsername}/manage-courses-support-poc:latest
    image: ${dockerHubUsername}/manage-courses-support-poc:latest
