default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV['DB_USERNAME'] || 'publish_courses_support' %>
  password: <%= ENV['DB_PASSWORD'] || 'publish_courses_support' %>
  host: <%= ENV['DB_HOSTNAME'] || 'localhost' %>
  port: <%= ENV['DB_PORT'] || '5432' %>

development:
  <<: *default
  database: <%= ENV['DB_DATABASE'] || 'publish_courses_support_development' %>

test:
  <<: *default
  database: <%= ENV['DB_DATABASE'] || 'publish_courses_support_test' %>

qa:
  <<: *default
  database: <%= ENV['DB_DATABASE'] || 'publish_courses_support_qa' %>

new_qa:
  <<: *default
  database: <%= ENV['DB_DATABASE'] || 'publish_courses_support_new_qa' %>

staging:
  <<: *default
  database: <%= ENV['DB_DATABASE'] || 'publish_courses_support_staging' %>

new_staging:
  <<: *default
  database: <%= ENV['DB_DATABASE'] || 'publish_courses_support_new_staging' %>  

production:
  <<: *default
  database: <%= ENV['DB_DATABASE'] %>
  username: <%= ENV['DB_USERNAME'] || 'postgres' %>
  password: <%= ENV['DB_PASSWORD'] %>

new_prod:
  <<: *default
  database: <%= ENV['DB_DATABASE'] || 'publish_courses_support_new_prod' %>  