default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: publish_courses_support_development
  username: publish_courses_support
  password: password1

test:
  <<: *default
  database: publish_courses_support_test
  username: publish_courses_support
  password: password1

production:
  <<: *default
  database: <%= ENV['DB_DATABASE'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOSTNAME'] %>
  port: <%= ENV['DB_PORT'] || '5432' %>
