development:
  adapter: postgresql
  encoding: unicode
  database: publish_courses_support_development
  pool: 5
  username: publish_courses_support
  password: password1

test:
  adapter: postgresql
  encoding: unicode
  database: publish_courses_support_test
  pool: 5
  username: publish_courses_support
  password: password1
